package com.dakiplast.enums;

public enum OrderInformationTypes {
	DOOR_SORT, DOOR_TYPE, DOOR_GLASS, THRESHOLD_SORT, MOSQUITO_SORT, MOSQUITO_TYPE, WINDOW_SORT, WINDOW_GLASS, SHUTTER_SORT,
	SHUTTER_BOX_SORT, SHUTTER_BOX_TYPE
}
